import HeroLink from '@/components/home/HeroLink'
import SkillLabel from '@/components/home/SkillLabel'
import Socials from '@/components/home/Socials'
import Navbar from '@/components/Navbar'
import Head from 'next/head'
import { FontAuthor } from './_app'

export default function Home() {
  return (
    <>
      <Head>
        <title>Adamrf.design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='h-screen flex flex-col'>
        <Navbar />

        <main className='text-adam-primary py-12 md:grid md:grid-cols-2 md:flex-grow'>


          <div id='about' className='flex flex-col gap-y-8 border-b md:border-none border-adam-primary px-6 md:px-28 pb-8'>
            <h2 className='text-4xl sm:text-5xl md:text-7xl font-bold'>Designer & Photography</h2>

            <div className={FontAuthor.className}>
              <h6 className='text-sm md:text-lg font-medium'>About me</h6>
              <p className='text-sm md:text-2xl leading-6'>Saya <span className='font-medium'>Adam</span>, saya sorang <span className='font-medium'>desainer dan fotografi</span> yang ada di semarang, Saya telah mengerjakan beberapa projek desain yang kebanyakan di bidang kuliner</p>
            </div>

            <div className={FontAuthor.className + ' text-sm md:text-base flex flex-row justify-end items-center gap-x-2'}>
              <span>Skill: </span>
              <SkillLabel text='figma' />
              <SkillLabel text='Adobe Illustrator' />
            </div>
          </div>



          <div id='links' className='grid grid-rows-3 text-center flex-grow'>
            <HeroLink text='Portofolio' href='/portofolio' />
            <HeroLink text='Services' href='/services' />
            <HeroLink text='Contact' href='/contact' />

            <Socials className='md:hidden' />
          </div>
        </main>
      </div>
    </>
  )
}
